# Generated by Django 5.1.5 on 2025-03-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_items_category_alter_subcategory_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='remain_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
